#!/usr/bin/env ruby
# encoding: UTF-8

require 'server'

# TODO Add a way to kill that.
begin
  Rack::Handler::WEBrick.run(Rack::Lint.new(FTServer::Server.new),
    :Port => 48067)
rescue Interrupt
  puts 'Stopping server.'
  exit
end
